config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  # For SSL Certificate
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      get  :show
      post :star
      post :mark_read
      get  :data
      get  :get_open_rewards
      post :reward
      post :request_reward

    end
    resources :rewards, only: [:create]
  end

  resources :rewards, only: [] do
    member do
      post :distribute
      post :accept
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  #Stripe
  post '/add_card', to: 'users#add_card'
  get  '/add_bank', to: 'users#add_bank'


  resources :pinned_searches

  get '/settings',      to: 'users#edit'

  get '/claims',      to: 'rewards#index'
  resources :users, only: [:update, :destroy, :add_card] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  REASON_LABELS = {
    'comment'        => 'primary',
    'author'         => 'success',
    'state_change'   => 'info',
    'mention'        => 'warning',
    'assign'         => 'danger',
    'subscribed'     => 'subscribed',
    'team_mention'   => 'team_mention',
    'security_alert' => 'security_alert'
  }.freeze

  STATE_LABELS = {
    'open'   => 'success',
    'closed' => 'danger',
    'merged' => 'subscribed'
  }

  SUBJECT_TYPES = {
    'RepositoryInvitation'         => 'mail-read',
    'Issue'                        => 'issue-opened',
    'PullRequest'                  => 'git-pull-request',
    'Commit'                       => 'git-commit',
    'Release'                      => 'tag',
    'RepositoryVulnerabilityAlert' => 'alert'
  }.freeze

  SUBJECT_STATUS = {
    success: "success",
    failure: "failure",
    error: "error",
    pending: "pending"
  }

  NOTIFICATION_STATUS_OCTICON = {
    'success' => 'check',
    'failure' => 'x',
    'error' => 'alert',
    'pending' => 'primitive-dot'
  }

  def filters
    {
      reason:       params[:reason],
      unread:       params[:unread],
      repo:         params[:repo],
      type:         params[:type],
      archive:      params[:archive],
      starred:      params[:starred],
      owner:        params[:owner],
      per_page:     params[:per_page],
      q:            params[:q],
      state:        params[:state],
      label:        params[:label],
      author:       params[:author],
      bot:          params[:bot],
      unlabelled:   params[:unlabelled],
      assigned:     params[:assigned],
      is_private:   params[:is_private],
      status:       params[:status],
      claim:        params[:claim],
      open_rewards: params[:open_rewards],
      your_rewards: params[:your_rewards]
    }
  end

  def inbox_selected?
    !archive_selected? && !starred_selected? && !showing_search_results? && !claim_selected? && !open_rewards_selected? && !your_rewards_selected?
  end

  def archive_selected?
    filters[:archive].present?
  end

  def open_rewards_selected?
    filters[:open_rewards].present?
  end

  def your_rewards_selected?
    filters[:your_rewards].present?
  end

  def claim_selected?
    filters[:claim].present?
  end

  def starred_selected?
    filters[:starred].present?
  end

  def showing_search_results?
    filters[:q].present?
  end

  def show_archive_icon?
    starred_selected? || showing_search_results?
  end

  def notification_param_keys
    filters.keys - [:per_page]
  end

  def bucket_param_keys
    [:archive, :starred]
  end

  def filter_param_keys
    notification_param_keys - bucket_param_keys
  end

  def any_active_filters?
    filter_param_keys.any?{|param| filters[param].present? }
  end

  def filtered_params(override = {})
    filters.merge(override)
  end

  def mute_button
    function_button('Mute', 'mute', "mute", 'Mute notification', false)
  end

  def delete_button
    function_button("Delete", 'trashcan', "delete", 'Delete notification', false)
  end

  def archive_button
    function_button("Archive", 'checklist', "archive_toggle archive", 'Archive', false)
  end

  def unarchive_button
    function_button("Unarchive", 'inbox', "archive_toggle unarchive", 'Unarchive notification', false)
  end

  def mute_selected_button
    function_button('Mute selected', 'mute', 'mute_selected', 'Mute selected items')
  end

  def mark_read_selected_button
    function_button('Mark as read', 'eye', 'mark_read_selected', 'Mark items as read')
  end

  def archive_selected_button
    function_button("Archive selected", 'checklist', "archive_toggle archive_selected", 'Archive selected items')
  end

  def create_reward_button
    function_button("Add Reward", 'credit-card', "create_reward", 'Create Reward')
  end

  def request_reward_button
    function_button("Request Reward", 'credit-card', "request_reward", 'Request Reward')
  end

  def accept_reward_button
    function_button("Accept Reward", 'credit-card', "accept_reward", 'Accept Reward')
  end

  def distribute_reward_button
    function_button("Distribute Reward", 'law', "distribute_reward", 'Distribute Reward')
  end

  def unarchive_selected_button
    function_button("Unarchive selected", 'inbox', "archive_toggle unarchive_selected", 'Unarchive selected items')
  end

  def delete_selected_button
    function_button("Delete selected", 'trashcan', "delete_selected", 'Delete selected items')
  end

  def select_all_button(cur_selected, total)
    button_tag(type: 'button', class: "select_all btn btn-sm btn-outline-dark hidden-button", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': "Number of items selected") do
      octicon('check', height: 16) +
        content_tag(:span, " #{cur_selected}", class: 'bold d-none d-md-inline-block ml-1') +
        " | " +
        content_tag(:span, " #{total}", class: 'd-none d-md-inline-block')
    end if cur_selected < total
  end

  def function_button(title, octicon, css_class, tooltip, hidden=true)
    button_tag(type: 'button', class: "#{css_class} btn btn-sm btn-outline-dark #{'hidden-button' if hidden}", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': tooltip ) do
      octicon(octicon, height: 16) + content_tag(:span, "#{title}", class: 'd-none d-md-inline-block ml-1')
    end
  end

  def no_url_filter_parameters_present
    notification_param_keys.all?{|param| params[param].blank? }
  end

  def notification_icon(subject_type, state = nil)
    state = nil unless display_subject?
    return 'issue-closed' if subject_type == 'Issue' && state == 'closed'
    return 'git-merge' if subject_type == 'PullRequest' && state == 'merged'
    SUBJECT_TYPES[subject_type]
  end

  def notification_icon_title(subject_type, state = nil)
    return subject_type.underscore.humanize if state.blank?
    "#{state.underscore.humanize} #{subject_type.underscore.humanize.downcase}"
  end

  def notification_icon_color(state)
    {
      'open' => 'text-success',
      'closed' => 'text-danger',
      'merged' => 'text-subscribed'
    }[state]
  end

  def reason_label(reason)
    REASON_LABELS.fetch(reason, 'secondary')
  end

  def state_label(state)
    STATE_LABELS.fetch(state, 'secondary')
  end

  def filter_option(param)
    if filters[param].present?
      link_to root_path(filters.except(param)), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def reason_filter_option(reason)
    if filters[:reason].present? && reason.present?
      reasons = filters[:reason].split(',').reject(&:empty?)
      index = reasons.index(reason.underscore.downcase)
      reasons.delete_at(index) if index
      link_to root_path(filters.merge(:reason => reasons.join(','))), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def filter_link(param, value, count)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, count: count) do
      yield
    end
  end

  def org_filter_link(param, value)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, except: :repo, link_class: 'owner-label') do
      yield
    end
  end

  def repo_filter_link(param, repo_name, count)
    active = params[param] == repo_name || params[:owner] == repo_name.split('/')[0]
    sidebar_filter_link(active: active, param: param, value: repo_name, count: count, except: :owner, link_class: 'repo-label', title: repo_name) do
      yield
    end
  end

  def sidebar_filter_link(active:, param:, value:, count: nil, except: nil, link_class: nil, path_params: nil, title: nil)
    content_tag :li, class: (active ? 'nav-item active' : 'nav-item'), title: title do
      active = (active && not_repo_in_active_org(param))
      path_params ||= filtered_params(param => (active ? nil : value)).except(except)
      link_to root_path(path_params), class: (active ? "nav-link active filter #{link_class}" : "nav-link filter #{link_class}") do
        yield
        if active && not_repo_in_active_org(param)
          concat content_tag(:span, octicon('x', :height => 16), class: 'badge badge-light')
        elsif count.present?
          concat content_tag(:span, count, class: 'badge badge-light')
        end
      end
    end
  end

  def reason_filter_link(value, count)
    active = params[:reason].present? && params[:reason].split(',').include?(value.to_s)
    link_value = reason_link_param_value(params[:reason], value, active)
    path_params = filtered_params(:reason => link_value)

    sidebar_filter_link(active: active, param: :reason, value: link_value, count: count, path_params: path_params) do
      yield
    end
  end

  def reason_link_param_value(param, value, active)
    reasons = param.try(:split, ',') || []
    active ? reasons.delete(value) : reasons.push(value)
    reasons.try(:join, ',')
  end

  def not_repo_in_active_org(param)
    return true unless param == :repo
    params[:owner].blank?
  end

  def search_query_matches?(query, other_query)
    query.split(' ').sort == other_query.split(' ').sort
  end

  def search_pinned?(query)
    return unless query.present?
    return false if current_user.pinned_searches.empty?

    current_user.pinned_searches.any? do |pinned_search|
      search_query_matches?(query, pinned_search.query)
    end
  end

  def notification_status(status)
    return unless status.present?
    content_tag(:span,
      octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: status),
      class: "badge badge-light badge-pr #{status}",
      title: status.humanize,
      data: {toggle: 'tooltip'}
    )
  end

  def sidebar_notification_status(status)
    octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: "sidebar-icon #{status}")
  end

  def notification_button(subject_type, state = nil)

app/views/notifications/_app_prompt.html.erb
<p>
  Pull in state, labels, authors, assignees and CI status on issues and pull requests by installing the GitHub App on
  <%= notification.repository_full_name %>.
</p>

<a href='<%= Octobox.config.app_url %>' class='btn btn-primary btn-sm'>Install the GitHub App</a>

app/views/notifications/_claim_rewards_rightbar.html.erb
<div>
  <div id="rightbar_reward_id">
    <div class="Subhead mt-0 mb-0">
      <h2 class="bounty-section">Accept your reward!</h2>
    </div>
    <div class="bounty-section" id="last-bounty-section" >
      <%= accept_reward_button %>
    </div>
  </div>
</div>

app/views/notifications/_help-box.html.erb
<div id="help-box" class="modal" role="dialog">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Keyboard shortcuts</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= render 'shared/keyboard_mappings' %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/_login_prompt.html.erb
<p>
  The GitHub App is installed on this repository, authorize it to see state, labels, authors, assignees and CI status on this notification.
</p>

<a href='/auth/githubapp' class='btn btn-primary btn-sm'>Login to the GitHub App</a>

app/views/notifications/_notification.html.erb
<tr id='notification-<%= notification.id %>' class='notification '>
  <td class='notification-checkbox align-middle'>
    <div class="custom-control custom-checkbox">
      <%= check_box_tag(
          "notification_#{notification.id}",
          notification.id,
          false,
          title: (notification.archived ? 'Unarchive' : 'Archive'),
          class: 'custom-control-input ' + (notification.archived ? 'unarchive' : 'archive')
        )
      %>
      <%= label_tag "notification_#{notification.id}", '', class: "custom-control-label" %>
    </div>
  </td>
  <td class='notification-star align-middle'>
    <%= octicon 'star', height: 18, class: "toggle-star #{notification.starred ? 'star-active' : 'star-inactive'}", data: { id: notification.id, toggle: 'tooltip' }, title: notification.starred ? 'Remove star' : 'Star' %>
  </td>

  <% if show_archive_icon? %>
    <td class='notification-archived align-middle'>
      <% if notification.archived? %>
        <%= octicon 'archive', height: 16, data: { toggle: 'tooltip' }, title: 'Archived' %>
      <% end %>
    </td>
  <% end %>

  <td class='notification-icon align-middle <%= notification_icon_color(notification.state) if notification.display_subject? %>'>
    <% if Octobox.github_app? && notification.subjectable? %>
      <% if notification.repository.try(:github_app_installed?) && !current_user.github_app_authorized? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Login to the GitHub App" data-content="<%= render 'login_prompt' %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% elsif !notification.repository.try(:github_app_installed?) %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Get more info for this <%= notification_icon_title(notification.subject_type, notification.state) %>" data-content="<%= render 'app_prompt', notification: notification %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% elsif Octobox.octobox_io? && notification.upgrade_required? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Subscribe Now" data-content="<%= render 'private_repos' %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% else %>
        <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16, title: notification_icon_title(notification.subject_type, notification.state), data: {toggle: 'tooltip'} %>
      <% end %>
    <% else %>
      <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16, title: notification_icon_title(notification.subject_type, notification.state), data: {toggle: 'tooltip'} %>
    <% end %>
  </td>
  <td class='notification-subject'>
    <%= link_to notification_link(notification), target: (Octobox.config.open_in_same_tab ? nil : '_blank'), rel: "noopener", class: 'subject-link link', onclick: "Octobox.markRead(#{notification.id})", data:{toggle:(notification.display_thread? ? 'showthread' : nil)}, title: notification.title do %>
        <%= notification.subject_title%>
        <%= octicon('link-external', class:'text-primary') unless notification.display_thread? %>
    <% end %>

    <% if notification.display_subject? %>
      <% if notification.subject %>
        <% notification.subject.labels.each do |label| %>
          <%= link_to emojify(label.name), root_path(filtered_params(label: label.name)), class: "badge d-sm", style: "background-color: ##{label.color}; color: #{label.text_color}" %>
        <% end %>
        <%= notification_status(notification.subject.status) %>
      <% end %>
    <% end %>
  </td>
  <td class='notification-reward-amount'>
    <small>
      $ <%= Reward.get_total_rewards_amount(notification.id, current_user) %>
    </small>
  </td>
  <% unless params[:repo].present? %>
    <td class='notification-repo'>
      <small>
        <%= link_to notification.repository_full_name, root_path(filtered_params(repo: notification.repository_full_name)), class: 'text-muted' %>
      </small>
    </td>
  <% end %>

  <td class='notification-subject-author'>
    <% if notification.display_subject? %>
      <% if notification.subject && notification.subject.author %>
        <small>
          <%= link_to notification.subject.author, root_path(filtered_params(author: notification.subject.author)), class: 'text-muted', title: 'Author', data: {toggle: 'tooltip'} %>
        </small>
      <% end %>
    <% end %>
  </td>

  <td class='notification-reason'>
    <%= link_to notification.reason.humanize, root_path(filtered_params(reason: notification.reason)), class: "badge badge-#{reason_label(notification.reason)}" %>
  </td>
  <td class='notification-date'>
    <small class='text-muted'>
      <%= local_relative_time(notification.updated_at, type: 'time-or-date') %>
    </small>

    <span class='buttons'>
      <% if notification.archived? %>
        <%= link_to(archive_selected_notifications_path(id: notification.id, value: false), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Unarchive' ) do %>
          <%= octicon('inbox', height: 15) %>
        <% end %>
      <% else %>
        <%= link_to(archive_selected_notifications_path(id: notification.id), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Archive' ) do %>
          <%= octicon('archive', height: 15) %>
        <% end %>
      <% end %>
      <%= link_to(mute_selected_notifications_path(id: notification.id), method: :post,  'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Mute' ) do %>
        <%= octicon('mute', height: 15) %>
      <% end %>
      <% if notification.archived? %>
        <%= link_to(delete_selected_notifications_path(id: notification.id), class: 'ml-1', method: :post, 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Delete' ) do %>
          <%= octicon('trashcan', height: 15) %>
        <% end %>
      <% end %>
    </span>
  </td>
</tr>

app/views/notifications/_reward.html.erb
<tr id='notification-<%= notification.id %>' class='notification' %>
  <td class='notification-checkbox align-middle'>
    <div class="custom-control custom-checkbox">
      <%= check_box_tag(
              "notification_#{notification.id}",
              notification.id,
              false,
              title: (notification.archived ? 'Unarchive' : 'Archive'),
              class: 'custom-control-input ' + (notification.archived ? 'unarchive' : 'archive')
          )
      %>
      <%= label_tag "notification_#{reward.notification.id}", '', class: "custom-control-label" %>
    </div>
  </td>

  <td class='notification-icon align-middle <%= notification_icon_color(reward.notification.state) if reward.notification.display_subject? %>'>
    <% if Octobox.github_app? && reward.notification.subjectable? %>
      <% if reward.notification.repository.try(:github_app_installed?) && !current_user.github_app_authorized? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Login to the GitHub App" data-content="<%= render 'login_prompt' %>">
          <%= octicon notification_icon(reward.notification.subject_type, reward.notification.state), :height => 16 %>
        </a>
      <% elsif !reward.notification.repository.try(:github_app_installed?) %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Get more info for this <%= notification_icon_title(reward.notification.subject_type, reward.notification.state) %>" data-content="<%= render 'app_prompt', notification: notification %>">
          <%= octicon notification_icon(reward.notification.subject_type, reward.notification.state), :height => 16 %>
        </a>
      <% elsif Octobox.octobox_io? && reward.notification.upgrade_required? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Subscribe Now" data-content="<%= render 'private_repos' %>">
          <%= octicon notification_icon(reward.notification.subject_type, reward.notification.state), :height => 16 %>
        </a>
      <% else %>
        <%= octicon notification_icon(reward.notification.subject_type, reward.notification.state), :height => 16, title: notification_icon_title(reward.notification.subject_type, reward.notification.state), data: {toggle: 'tooltip'} %>
      <% end %>
    <% else %>
      <%= octicon notification_icon(reward.notification.subject_type, reward.notification.state), :height => 16, title: notification_icon_title(reward.notification.subject_type, reward.notification.state), data: {toggle: 'tooltip'} %>
    <% end %>
  </td>
  <td class='notification-subject'>
    <%= link_to notification_link(reward.notification), target: (Octobox.config.open_in_same_tab ? nil : '_blank'), rel: "noopener", class: 'subject-link link', onclick: "Octobox.markRead(#{reward.notification.id})", data:{toggle:(reward.notification.display_thread? ? 'showthread' : nil)}, title: reward.notification.title do %>
      <%= reward.notification.subject_title%>
      <%= octicon('link-external', class:'text-primary') unless reward.notification.display_thread? %>
    <% end %>

    <% if reward.notification.display_subject? %>
      <% if reward.notification.subject %>
        <% reward.notification.subject.labels.each do |label| %>
          <%= link_to emojify(label.name), root_path(filtered_params(label: label.name)), class: "badge d-sm", style: "background-color: ##{label.color}; color: #{label.text_color}" %>
        <% end %>
        <%= notification_status(reward.notification.subject.status) %>
      <% end %>
    <% end %>
  </td>
  <td class='notification-reward-amount'>
    <small>
      $ <%= reward.amount %>
    </small>
  </td>
  <% unless params[:repo].present? %>
    <td class='notification-repo'>
      <small>
        <%= link_to reward.notification.repository_full_name, root_path(filtered_params(repo: reward.notification.repository_full_name)), class: 'text-muted' %>
      </small>
    </td>
  <% end %>

  <td class='notification-date'>
    <small class='text-muted'>
      <%= local_relative_time(reward.start_date, type: 'time-or-date') %>
    </small>

    <span class='buttons'>
      <% if reward.notification.archived? %>
        <%= link_to(archive_selected_notifications_path(id: reward.notification.id, value: false), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Unarchive' ) do %>
          <%= octicon('inbox', height: 15) %>
        <% end %>
      <% else %>
        <%= link_to(archive_selected_notifications_path(id: reward.notification.id), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Archive' ) do %>
          <%= octicon('archive', height: 15) %>
        <% end %>
      <% end %>
      <%= link_to(mute_selected_notifications_path(id: reward.notification.id), method: :post,  'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Mute' ) do %>
        <%= octicon('mute', height: 15) %>
      <% end %>
      <% if reward.notification.archived? %>
        <%= link_to(delete_selected_notifications_path(id: reward.notification.id), class: 'ml-1', method: :post, 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Delete' ) do %>
          <%= octicon('trashcan', height: 15) %>
        <% end %>
      <% end %>
    </span>
  </td>
</tr>

app/views/notifications/_reward_list.html.erb
<div class="card card-notifications">
  <div class="card-header sticky-top">
    <% if @rewards.to_a.any? %>
      <div class="per-page btn-group float-right d-block" data-toggle="tooltip" data-placement="left" title="Issues per page">
        <button type="button" class="btn btn-sm btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= @per_page %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right text-right">
          <% %w(20 40 60 80 100).map do |pagination_interval| %>
            <%= link_to pagination_interval, root_path(filtered_params(per_page: pagination_interval.to_i)), class: "dropdown-item #{'active' if @per_page == pagination_interval.to_i}" %>
          <% end %>
        </ul>
      </div>
    <% end %>
    <button id='sidebar_toggle' type="button" class="d-inline-block d-xl-none btn btn-sm btn-outline-dark" data-toggle="offcanvas" aria-label='Toggle sidebar'>
      <%= octicon 'three-bars', :height => 16 %>
    </button>
    <%# if @rewards.to_a.any? %>
<!--      <div class="custom-control custom-checkbox select-all d-inline-block">-->
<!--        <input id="select_all" type="checkbox" class='custom-control-input js-select_all' aria-label='Select All'>-->
        <%#= label_tag "select_all", '', class: "custom-control-label" %>
<!--      </div>-->
      <%#= select_all_button(@cur_selected, @total) %>
    <%# end %>
    <%= link_to sync_notifications_path(filters), class: "btn btn-sm btn-outline-dark js-sync #{'js-async' if Octobox.background_jobs_enabled?}", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-turbolinks' => false, 'data-animation' => 'false', 'data-position' => 'bottom', 'title' => 'Sync', 'aria-label' => 'Sync' do %>
      <%= octicon 'sync', height: 16, class: "#{'spinning' if initial_sync? || current_user.syncing?}" %>
    <% end %>

    <% if current_user.last_synced_at %>
      <span class='text-muted d-none d-sm-inline-block'>
        <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
      </span>
    <% end %>
  </div>

  <table class='table table-hover table-notifications js-table-notifications mb-0 <%= 'filtered' if any_active_filters? %>' data-refresh-interval=<%= current_user.effective_refresh_interval %>>
    <% if @rewards.to_a.any? %>
      <%= render partial: 'notification', collection: @rewards %>
    <% else %>
      <div class="py-5 text-center">
        <%= octicon 'search', height: 32, class: 'blankslate-icon' %>
        <h3>Nothing to see here.</h3>
        <p>Try writing code for an issue with a reward to win a reward.</p>
        <% unless current_user.notifications.any? %>
          <p><i>Expecting notifications? Make sure <a href="<%= Octobox.config.github_domain %>/settings/notifications">Web Notifications</a> are enabled on your GitHub account.</i></p>
        <% end %>
      </div>
    <% end %>
  </table>
</div>

app/views/notifications/show.html.erb
<% if current_user.syncing? %>
  <span class="js-is_syncing"><!-- This causes the sync icon to spin --></span>
<% end %>
<span class='js-unread-count' data-count="<%= @unread_count %>"></span>

<div class="flex-content">
  <div class="flex-sidebar">
    <%= render "sidebar" %>
  </div>
  <div class="flex-main show-thread">
    <%= render "list" %>
  </div>
  <div id='thread' class='flex-thread'>
   <%= render 'thread' %>
  </div>
</div>

<%= render 'help-box' %>