config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  # For SSL Certificate
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      get  :show
      post :star
      post :mark_read
      get  :data
      get  :get_open_rewards
      post :reward
      post :request_reward

    end
    resources :rewards, only: [:create]
  end

  resources :rewards, only: [] do
    member do
      post :distribute
      post :accept
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  #Stripe
  post '/add_card', to: 'users#add_card'
  get  '/add_bank', to: 'users#add_bank'


  resources :pinned_searches

  get '/settings',      to: 'users#edit'

  get '/claims',      to: 'rewards#index'
  resources :users, only: [:update, :destroy, :add_card] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/views/shared/_keyboard_mappings.html.erb
<table class="keyboard-mappings">
  <tbody>
    <tr>
      <td class="keys">
        <div class="key">.</div> or <div class="key">r</div>
      </td>
      <td>
        Refresh
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">j</div>
      </td>
      <td>
        Move down the list
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">k</div>
      </td>
      <td>
        Move up the list
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">s</div>
      </td>
      <td>
        Star current notification
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">x</div>
      </td>
      <td>
        Mark current notification
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">a</div>
      </td>
      <td>
        Select/deselect all
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">y</div> or <div class="key">e</div>
      </td>
      <td>
        Archive current/marked notification(s)
      </td>
    </tr>
    <tr>
    <tr>
      <td class="keys">
        <div class="key">m</div>
      </td>
      <td>
        Mute current/marked notification(s)
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">d</div>
      </td>
      <td>
        Mark current/marked notification(s) as read here and on GitHub
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">#</div>
      </td>
      <td>
        Delete current/marked notification(s)
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">o</div> or <div class="key">Enter</div>
      </td>
      <td>
        Open current notification in a new window
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">?</div>
      </td>
      <td>
        Show this help menu
      </td>
    </tr>
    <tr>
      <td class="keys">
        <div class="key">esc</div>
      </td>
      <td>
        Close modal, thread OR clear filters
      </td>
    </tr>
  </tbody>
</table>

app/views/shared/_repo_scope_modal.html.erb
<% unless Octobox.fetch_subject? || Octobox.personal_access_tokens_enabled? %>
  <div id="repo-scope" class="modal" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Repository scope required</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <p>
            This feature requires additional permissions.
            <% if Octobox.octobox_io? %>
              <%= link_to 'Install the GitHub App', Octobox.config.app_url %> to enable them.
            <% else %>
              See the <%= link_to 'documentation', documentation_path(anchor: 'accessing') %> for how to enable them.
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_search_prefixes.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>
        <code>repo:octobox/octobox</code>
      </td>
      <td>Only search notifications from the octobox/octobox repository.</td>
    </tr>
    <tr>
      <td>
        <code>owner:microsoft</code>
      </td>
      <td>Only search notifications from repos in the microsoft organisation.</td>
    </tr>
    <tr>
      <td>
        <code>type:pull_request</code>
      </td>
      <td>
        Only search pull requests. Also accepts:
        <code>issue</code>,
        <code>release</code>,
        <code>commit</code>,
        <code>repository_invitation</code>
        and <code>repository_vulnerability_alert</code>.
      </td>
    </tr>
    <tr>
      <td>
        <code>reason:mention</code>
      </td>
      <td>
        Filter by reason the notification was triggered. Also accepts:
        <code>comment</code>,
        <code>author</code>,
        <code>state_change</code>,
        <code>assign</code>,
        <code>subscribed</code>,
        <code>team_mention</code>,
        <code>security_alert</code>.
      </td>
    </tr>
    <tr>
      <td>
        <code>starred:true</code>
      </td>
      <td>Search notifications that you've starred. Also accepts false for the inverse.</td>
    </tr>
    <tr>
      <td>
        <code>archived:true</code>
      </td>
      <td>Search notifications that you've archived. Also accepts false for the inverse.</td>
    </tr>
    <tr>
      <td>
        <code>inbox:true</code>
      </td>
      <td>Search notifications in your inbox. Also accepts false for the inverse.</td>
    </tr>
    <tr>
      <td>
        <code>unread:true</code>
      </td>
      <td>Search unread notifications.  Also accepts false for the inverse.</td>
    </tr>
    <tr>
      <td>
        <code>muted:true</code>
      </td>
      <td>Search muted notifications.  Also accepts false for the inverse.</td>
    </tr>
    <tr>
      <td>
        <code>sort:updated</code>
      </td>
      <td>Sort notifications by <code>updated</code>, <code>read</code> or <code>subject</code>.</td>
    </tr>
    <tr>
      <td>
        <code>order:asc</code>
      </td>
      <td>Sort notifications in ascending (<code>asc</code>) or descending (<code>desc</code>) order. Use with <code>sort</code>.</td>
    </tr>
    <% if display_subject? %>
      <tr>
        <td>
          <code>state:open</code>
        </td>
        <td>
          Filter by notifications from issues or pull requests that are open.
          Also accepts <code>closed</code> and <code>merged</code>.
        </td>
      </tr>
      <tr>
        <td>
          <code>label:bug</code>
        </td>
        <td>Filter by notifications from issues or pull requests with the label of '<code>bug</code>'.</td>
      </tr>
      <tr>
        <td>
          <code>author:andrew</code>
        </td>
        <td>Filter by notifications from issue or pull requests that were created by '<code>andrew</code>'.</td>
      </tr>
      <tr>
        <td>
          <code>status:success</code>
        </td>
        <td>
          Filter by notifications from pull requests where checks status is '<code>success</code>'.
          Also accepts <code>failure</code>, <code>pending</code> and <code>error</code>.
        </td>
      </tr>
      <tr>
        <td>
          <code>unlabelled:true</code>
        </td>
        <td>Search notifications that don't have any labels.</td>
      </tr>
      <tr>
        <td>
          <code>bot:true</code>
        </td>
        <td>Search notifications generated by GitHub apps or bot users (name ends in '<code>-bot</code>').</td>
      </tr>
      <tr>
        <td>
          <code>private:true</code>
        </td>
        <td>Search notifications from private repositories. Also accepts false for the inverse.</td>
      </tr>
      <tr>
        <td>
          <code>assignee:andrew</code>
        </td>
        <td>Filter by notifications from issue or pull requests that are assigned to '<code>andrew</code>'.</td>
      </tr>
      <tr>
        <td>
          <code>locked:true</code>
        </td>
        <td>Search for lock conversations. Also accepts false for the inverse.</td>
      </tr>
      <tr>
    <% end %>
  </tbody>
</table>