config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  # For SSL Certificate
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      get  :show
      post :star
      post :mark_read
      get  :data
      get  :get_open_rewards
      post :reward
      post :request_reward

    end
    resources :rewards, only: [:create]
  end

  resources :rewards, only: [] do
    member do
      post :distribute
      post :accept
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  #Stripe
  post '/add_card', to: 'users#add_card'
  get  '/add_bank', to: 'users#add_bank'


  resources :pinned_searches

  get '/settings',      to: 'users#edit'

  get '/claims',      to: 'rewards#index'
  resources :users, only: [:update, :destroy, :add_card] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/views/pages/_features.html.erb
<ul class="list-group list-group-flush pr-0">
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited private repositories</li>
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited public repositories</li>
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited collaborators</li>
</ul>

app/views/pages/_github.html.erb
<div class="pricing card mx-3 shadow p-3 mb-5 bg-white rounded text-muted">
  <%= render('pages/ribbon')%>
  <div class="card-body">
  	<p class='text-muted'>GitHub Marketplace - coming soon</p>
    <h5 class="card-title">Support the company</h5>
    <h6 class="card-subtitle mb-2 text-muted">Buy from the GitHub marketplace.</h6>
    <p class="card-text">Private repository access</p>
    <%= render('pages/features') %>
	  <div class='d-flex align-items-center border-top border-bottom py-2 mt-3 mb-3 d-flex flex-md-items-center flex-justify-between'>
	  	<span class="price pr-2">$100</span>
	  	<span class="text-small text-muted d-block mt-1 mt-md-0">/ month</span>
	  </div>
	  <a href='#' title='Coming soon' data-toggle='tooltip' class='btn btn-success w-100 disabled'>Purchase on GitHub</a>
	  <p class='text-muted'><small>Next: confirm your purchase on GitHub</small></p>
  </div>
</div>

app/views/pages/_opencollective.html.erb
<div class="pricing card mx-3 shadow p-3 mb-5 bg-white rounded">
  <%= render('pages/ribbon') %>
  <div class="card-body">
  	<p class='text-muted'>Open Collective</p>
    <h5 class="card-title">Support the community</h5>
    <h6 class="card-subtitle mb-2 text-muted">Pay by donation on Open Collective.</h6>
    <p class="card-text">Private repository access</p>
    <%= render('pages/features') %>
	  <div class='d-flex align-items-center border-top border-bottom py-2 mt-3 mb-3 d-flex flex-md-items-center flex-justify-between'>
	  	<span class="price pr-2">$100</span>
	  	<span class="text-small text-muted d-block mt-1 mt-md-0">/ month</span>
	  </div>
	  <a href='https://opencollective.com/octobox' target='_blank' class='btn btn-success w-100'>Donate on Open Collective</a>
	  <p class='text-muted'><small>Next: make your donation on Open Collective</small></p>
  </div>
</div>

app/views/pages/_ribbon.html.erb
<div class='ribbon primary'>
  <span>Free for oss</span>
</div>

app/views/pages/documentation.html.erb
<div class='flex-content'>
  <div class="flex-sidebar">
    <div id='sidebar' class="list-group list-group-flush flex-column pt-5">
      <a class='list-group-item list-group-item-action' href='#documentation'>Documentation</a>
      <a class='list-group-item list-group-item-action' href='#accessing'>Accessing Speed</a>
      <a class='list-group-item list-group-item-action' href='#using'>Using Speed</a>
      <a class='list-group-item list-group-item-action' href='#navigating'>Navigating Speed</a>
      <a class='list-group-item list-group-item-action' href='#searching'>Searching Speed</a>
      <a class='list-group-item list-group-item-action' href='#api'>API Documentation</a>
      <a class='list-group-item list-group-item-action' href='#support'>Support</a>
    </div>
  </div>

  <div class="flex-main">
    <div class="card">
      <div class='card-header d-lg-none sticky-top'>
        <button id='sidebar_toggle' type="button" class="btn btn-sm btn-outline-dark" data-toggle="offcanvas" aria-label='Toggle sidebar'>
          <%= octicon 'three-bars', :height => 16 %>
        </button>
      </div>
      <div class='card-body'>
        <h1 id='documentation' class="text-left">Documentation</h1>
        <hr>
        <p>
          Speed helps you triage notifications efficiently so you can spend less time managing and more time getting things done.
        </p>
        <p>
          If you manage more than one active project on GitHub, you probably find <a href="https://github.com/notifications">GitHub Notifications</a> pretty lacking. Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on. Most open source maintainers (and some GitHub staff) end up using a complex combination of filters and labels in their mail client to manage their notifications from their inbox. If, like us, you try to avoid email, then Speed is for you.
        </p>
        <h2 id='accessing'>Accessing Speed</h2>
        <hr>
        <% if Octobox.octobox_io? %>
          <p>
            This instance of Speed is hosted by the Speed.io team. To access Speed.io you just need to sign in with your GitHub profile or install the GitHub app on the <%= link_to 'homepage', root_path %>.
          </p>
          <h3>Signing in with GitHub</h3>
          <p>
             This will give you access to basic notification information for public <i>and</i> private repositories using GitHub's <code>notification</code> scope. <% if Octobox.octobox_io? %> To access more detailed information you need to install the Speed.io GitHub App. <% end %>
          </p>
          <% if Octobox.octobox_io? %>
            <h3>Installing the GitHub App</h3>
            <p>
              To access more detailed information about your notifications (assignees, labels, conversations threads etc) Speed.io needs more privileged access to your repositories. To enable this you need to install our GitHub App for your personal or organisation's account. Access to public repositories on Speed.io is free forever, access to private repositories is a paid-for service.
            </p>
            <h3>Paying for private repository access</h3>
            <p>
              There are two ways to pay for private repo access on Speed.io:
            </p>
            <ul>
              <li>
                By making a donation of X or more each month to the Speed community through <a href="https://opencollective.com/octobox">Open Collective</a>
              </li>
              <li>
                By paying X per Y through the GitHub Marketplace, which is charged monthly to your GitHub account.
              </li>
            </ul>
            <p>
              This may seem a little strange, but bear with us: As a social experiment in open source sustainability we are asking you to make a choice between supporting the community of maintainers and contributors, or supporting the commercial entity that operates Speed.io. The service you'll receive will be <i>exactly the same</i> regardless of the way you pay. You can read more about why we think this is important <a href='#todo'>over on our blog</a>.
            </p>
          <% end %>
          <h3>Host your own Speed</h3>
          <p>
            Alternatively you can host your own instance of Speed. See <a href='#https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md'>the installation guide</a> for instructions and details regarding deployment to Heroku, Docker, and more.
          </p>
        <% end %>
        <% unless Octobox.octobox_io? %>
          <p>
            By default Speed uses GitHub's basic OAuth <code>'notifications'</code> scope to access your notifications. This provides Octobox with access to notifications from both public <i>and</i> private repositories, but it provides very little detail about those notifications.
          </p>
          <p>
            In order to access more detailed information about your notifications Speed needs to enable the <code>repo</code> scope on GitHub. You can do this by:
          </p>
          <ul>
            <li><a href='https://github.com/daljeetv/speed/blob/master/docs/INSTALLATION.md#using-personal-access-tokens'>Using a personal access token</a></li>
            <li><a href='https://github.com/daljeetv/speed/blob/master/docs/INSTALLATION.md#customizing-the-scopes-on-github'>Customising the GitHub scope environment variable</a></li>
          </ul>
        <% end %>
        <h2 id='using'>Using Speed</h2>
        <hr>
        <p>
          Speed helps you triage notifications from GitHub. If you use GitHub's own notifications dashboard you'll be familiar with some of the interface, actions etc. but there are some important differences:
        </p>
        <h3>Archiving</h3>
        <p>
          Speed extends GitHub's notification model by providing an additional 'archived' status, much like Gmail's email client. Archived notifications will not appear in your inbox again unless the thread, issue or PR receives a new notification. Archiving a notification does not result in any action on GitHub.
        </p>
        <h3>Starring</h3>
        <p>
          Speed also adds a starred status to help you highlight important notifications with a star so you can come back and find them easily. Starred notifications are not social, they are more like bookmarks that GitHub stars. Starring a notification does not result in any action on GitHub.
        </p>
        <h3>Muting</h3>
        <p>
          Muting a notification will mark the notification as read, move it to the archive <i>and</i> ignore all further notifications from this thread, issue or PR. Muting also sets the thread to <code>ignore:true</code> ignoring further notifications on GitHub too.
        </p>
        <h3>Syncing</h3>
        <p>
          By default Speed will synchronise every time you hit the synchronise button.
          <% if Octobox.config.minimum_refresh_interval %>
            You can set automatic refresh interval on the <%= link_to 'settings page', settings_path %>.
          <% end %>
        </p>
        <h2>Shortcuts</h2>
        <hr>
        <p>
          Speed features a full set of keyboard shortcuts inspired by Gmail:
        </p>
        <%= render 'shared/keyboard_mappings' %>
        <h2 id='navigating'>Navigating Speed</h2>
        <hr>
        <p>
          The sidebar contains most of the things you'll need to navigate between views in Speed:
        </p>
        <table class='table table-responsive'>
          <tr>
            <td>Archived</td>
            <td>Notifications that you've archived won't appear in your inbox again until Speed receives another notification regarding that thread, issue or PR.</td>
          </tr>
          <tr>
            <td>
              Starred
            </td>
            <td>
              Notifications that you've starred are gathered together so you can come back and find them easily.
            </td>
          </tr>
          <tr>
            <td>
              Read/unread
            </td>
            <td>
              Notifications that have yet to be read or have been read, respectively. Nothing new here.
            </td>
          </tr>
          <tr>
            <td>
              Type
            </td>
            <td>
              Notifications by type (commit, issue, pull request, release, etc)
            </td>
          </tr>
          <tr>
            <td>
              Reason
            </td>
            <td>
              Notifications by the reason you've received it (assigned, authored, commented, mentioned, review requested, state changed or subscribed).
            </td>
          </tr>
          <tr>
            <td>
              Org/repo
            </td>
            <td>
              Notifications from a particular organisation and/or repo.
            </td>
          </tr>
          <tr>
            <td>
              State
            </td>
            <td>
              <%= repo_scope_modal %> The state of the underlying issue or PR. i.e. open, closed, merged,
            </td>
          </tr>
          <tr>
            <td>
              Assignee
            </td>
            <td>
              <%= repo_scope_modal %> Notifications assigned to you.
            </td>
          </tr>
          <tr>
            <td>
              Status
            </td>
            <td>
              <%= repo_scope_modal %> The current CI status of the underlying PR. i.e. Success, Failing, Pending
            </td>
          </tr>
          <tr>
            <td>
              Bots
            </td>
            <td>
             <%= repo_scope_modal %> Notifications created by bots.
            </td>
          </tr>
          <tr>
            <td>
              Unlabelled
            </td>
            <td>
              <%= repo_scope_modal %> Notifications that have not been labeled.
            </td>
          </tr>
          <tr>
            <td>
              Visibility
            </td>
            <td>
             <%= repo_scope_modal %> Notifications from public or private repositories.
            </td>
          </tr>
        </table>

        <h2 id='searching'>Searching Speed</h2>
        <hr>
        <p>
          Speed's search bar supports the following filter prefixes. Combine them together and with free text searches, for example: <code>"github enterprise type:issue owner:speed reason:assign"</code>:
        </p>
        <p>
          Many prefixes accept multiple arguments when separated by commas or passed twice, for example:<br/>
          "<code>type:issue,release owner:speed owner:24pullrequests</code>".
        </p>
        <p>
          Some prefixes also can be negated to exclude certain types of results, for example:<br/>
          "<code>-repo:splitrb/split -type:commit -owner:speed -reason:mention</code>".
        </p>
        <h5>Supported prefixes</h5>
        <%= render 'shared/search_prefixes' %>

        <h2 id='api'>API Documentation</h2>
        <hr>
        <p>
          Access to the <a href='/docs'>Speed API</a> requires a key which you can generate and regenerate from the <%= link_to 'settings page', settings_path %>.
        </p>

        <h2 id='support'>Support</h2>
        <hr>
        <p>
         Please <a href='mailto:support@speed.io'>email us</a>. You can also
        </p>
        <ul>
          <li>File an issue in our <a href='https://github.com/daljeetv/speed/issues/new'>bug tracker</a> following the template provided.</li>
          <li>Ask for help in our <a href='https://gitter.im/speed/speed'>public chat room</a>.</li>
          <li>Email us at <%= mail_to 'daljeetv@gmail.com' %>.</li>
          <li>Tweet us at <%= link_to '@speedio', 'https://twitter.com/speedio' %>.</li>
        </ul>
      </div>
    </div>
    <%= render 'layouts/footer'%>
  </div>
</div>

<%= render 'shared/repo_scope_modal' %>

app/views/pages/home.html.erb
<br class="container readable">
  <div class='container readable text-center'>
    <%#= image_tag 'screenshot.png', class: 'screenshot mt-3', alt: 'Screenshot' %>
    </p>
    <p>
      <%= link_to login_path, class: 'btn btn-outline-dark btn-lg' do %>
        <%= octicon 'mark-github', height: 22 %>
        <span class='ml-1'>Sign in with GitHub</span>
      <% end %>
      <% if Octobox.github_app? %>
        <%= link_to Octobox.config.app_url, class: 'btn btn-outline-dark btn-lg' do %>
          <%= octicon 'briefcase', height: 22 %>
          <span class='ml-1'>Install the GitHub App</span>
        <% end %>
      <% end %>
    </p>
  </div>

  <div class="container readable my-5">
    <h3 id='features'>Features</h3>
<!--    <h5 class='mb-5 text-muted font-weight-light'>Speed lets you add rewards to GitHub Issues</h4>-->
     <div class="card shadow-sm mb-3">
      <div class="card-body">
        <div class="media">
          <div class="align-self-center mr-4">
            <%= octicon 'rocket', height: 50 %>
          </div>
          <div class="media-body">
            <h5>Get your issues solved fast</h5>
            Speed let's you add rewards to Github issues so your issues are solved faster.
          </div>
        </div>
      </div>
    </div>
    <div class="card shadow-sm mb-3">
      <div class="card-body">
        <div class="media">
          <div class="align-self-center mr-4">
            <%= octicon 'octoface', height: 50 %>
          </div>
          <div class="media-body">
            <h5>Increase Software Engineering Horsepower On Demand</h5>
            Just file incentivized issues and your applications will be built by the fastest and smartest developers on the planet.
          </div>
        </div>
      </div>
    </div>
    <div class="card shadow-sm mb-3">
      <div class="card-body">
        <div class="media">
          <div class="align-self-center mr-4">
            <%= octicon 'credit-card', height: 50 %>
          </div>
          <div class="media-body">
            <h5>Support Open Source</h5>
            80% of the code running in production at today's enterprises is open source. Speed is a great way to support the makers of this world class software.
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

  <% if Octobox.octobox_io? %>
    <div class="container readable mb-5">

      <h3 id='pricing' class='pt-4'>Pricing</h3>
      <p class='pt-3 text-large'>Speed is <b>free for open source</b> projects. To add private repository access to your personal or organisation's account:</p>
      <div class='d-flex flex-column flex-lg-row pt-3 justify-content-center'>
        <%= render('pages/opencollective')%>
        <%= render('pages/github')%>
      </div>
      <p class='text-large'>Wondering why there are two options? <a href='/pricing#why'>Read more about our pricing strategy</a>.</p> 

      <h3 id='users' class='pt-4'>Used by developers from</h3>
      <div class="row mt-4">
        <div class="col">
          <% used_by_orgs.each do |org| %>
            <%= image_tag "https://github.com/#{org}.png?w=120", width: 60, height: 60, class: 'inline-block mr-2 mb-3', title: org, data: {toggle: 'tooltip'} %>
          <% end %>
        </div>
      </div>

    </div>
  <% end %>

  </div>
</div>

<%= render 'layouts/footer'%>
<script async defer src="https://buttons.github.io/buttons.js"></script>

app/views/pages/pricing.html.erb
<div class='container readable mt-5'>
	<h1 class="text-center"><%= octobox_round(80) %> Octobox</h1>
	<h3 class='pt-3 text-center'>One product, two ways to pay</h3>
    <p class='pt-3 text-large'>Octobox is <b>free for open source</b> projects. To add private repository access to your personal or organisation's account:</p>
	
    <div class='d-flex flex-column flex-lg-row pt-3 justify-content-center'>
		<%= render('opencollective')%>
		<%= render('github')%>
	</div>
	
	<h2 id='why' class='text-center mb-5 pt-3'>What... Why?</h2>

	<h5>An experiment in open source sustainability</h5>

    <p>Like many open source projects Octobox currently relies on volunteers and donations to cover the cost of maintaining the Octobox project. This is <a href='https://www.fordfoundation.org/about/library/reports-and-studies/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure/'>not sustainable</a>.

    <p>Octobox is primarily maintained by Andrew Nesbitt and Benjamin Nickolls. We believe that many of the issues around the sustainability of open source software <i>can</i> be solved by the community itself. We also believe in leading by example, testing our assumptions and backing up our decisions with data.</p>

    <p>Octobox has a small community of <a href='https://github.com/orgs/octobox/people'>maintainers</a>, <a href='https://github.com/octobox/octobox/graphs/contributors'>contributors</a>, <a href='https://opencollective.com/octobox/#contributors'>supporters and sponsors</a>. Our first priority is to begin building a sustainable income, for ourselves and our community. Our second is to demonstrate that our approach is repeatable and scalable, proving that we can solve this problem <i>together</i>. Our pricing model is our first experiment.

    <h5 class='pt-3'>Do you prefer supporting a commercial provider, or the community itself?</h5>
    <p>Octobox.io operated by Octobox Ltd. a company registered in the UK by Andrew Nesbitt and Benjamin Nickolls. The company is primarily designed to offer limited liability to the operators of Octobox.io and to renumerate directors and staff as employees or contractors.</p>

    <p>The Octobox project will continue to collect donations via Open Collective and operate a transparent ledger of income and outgoings for the project — including, for the time being, the costs of hosting Octobox.io. When it is able the project will pay maintainers for their time including time spent operating Octobox.io, which will be directed through Octobox Ltd.</p>

    <p>Octobox Ltd. will provide private repository access to those who donate an equivalent sum (or more) to the community as pay directly through alternate channels. In addition the company will pledge at least 15% of its revenues for use by the community to further the open source project, forever.</p>

    <h5 class='pt-3'>Why does this matter?</h5>

    <p>Most open source projects struggle to navigate the legislative, legal and social issues around sustianing their projects. By diving straight into the deep end and documenting our experiences we hope to provide a blueprint for others to follow.</p>

    <p>By asking you to make the choice with how you pay we will demonstrate whether donation-based, community-first sustainabiliy strategies work over more classical, commercial-lead approaches.</p>

    <p>Thanks for taking the time to read this. If anything is unclear or you have concerns about this please <a href='https://github.com/octobox/octobox/issues/new'>raise an issue</a> or <a href='mailto: hello@octobox.io'>get in touch</a>.</p>
</div>

<%= render 'layouts/footer'%>

app/views/pages/privacy.html.erb
<div class="container readable mt-5">
  <div class='d-flex align-items-end justify-content-between'>
    <h1>Privacy Policy</h1>
    <%= link_to octobox_round(80), root_path  %>
  </div>
  <hr>

  <h2>We Care About Your Privacy</h2>
  <p>
    No, really, we actually do. But as a young, growing service provider it is necessary for Octobox.io to store some data. If we do so it will be for one of two reasons:
  </p>
  <ul>
    <li>To enable you to use the service effectively.</li>
    <li>To enable us to improve the services you can use.</li>
  </ul>

  <h3>Data We Collect</h3>
  <p>
    We collect the e-mail addresses of those who sign up with Octobox.io, aggregate information on what pages users access or visit, and information volunteered by the consumer.
  </p>
  <p>
    We collect information about your GitHub notifications including some basic data about notifications from private repositories. If you install the GitHub App we collect more detailed data about these notifications including but not limitted to authors, labels, comments and status. If you enable private repository access then we collect this data for your private repositories too.
  </p>

  <h3>Transmitting Your Data</h4>
  <p>
    Transmitting information over the Internet is generally not completely secure, and we can’t guarantee the security of your data.
  </p>

  <h3>Processing And Storing Your Data</h4>
  <p>
    Your data is processed by servers in France and Ireland. Your data is stored on our servers in France, once it is stored we have processes in place to secure it.
  </p>

  <h3>Sharing Your Data</h4>
  <p>
    The information we collect is not shared with or sold to other organizations, except to provide products or services you have requested, with your permission, or under the following circumstances:
  </p>
  <ul>
    <li>
      It is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Service, or as otherwise required by law.
    </li>
    <li>
      We transfer information about you if the assets of Octobox.io are acquired by or merged with another organisation. In this event, Octobox.io will notify you before information about you is transferred and becomes subject to a different privacy policy.
    </li>
  </ul>
  <p>
    Other than the above declarations we won’t share your information with any other organisations for marketing, market research or commercial purposes, and we don’t pass on your details to other websites.
  </p>


  <h2>Services We Use</h2>
  <p>
    Like many other websites, we sometimes use cookies, Google Analytics and Bugnag to help us make our websites better.
  </p>
  <p>
    These tools are very common and widely used by other sites, but they do have privacy implications. When you visit sites that use these tools, you are potentially telling companies such as Google that you visited, as well as some information about how your web browser is configured. If you don’t want to share your browsing activities on sites with other companies, you can install opt-out browser plugins. You might find this article useful: <a href="http://www.guardian.co.uk/technology/askjack/2011/jun/17/ask-jack-internet-privacy-web-browsers-cookies">The Guardian – How to Keep Your Privacy Online</a>.
  </p>

  <h3>Cookies</h3>
  <p>
    Cookies are small amounts of text stored on your computer's web browser that can be written by websites and read by websites. They can also be shared between websites. We use cookies to store some information about your current session, this enables us to do things like keep you logged into the website between pages. Cookies are also used by third-party providers like Google:
  </p>

  <h3>Analytics</h3>
  <p>
    We use Google Analytics to collect information about how people use this site. Google Analytics stores information such as what pages you visit, how long you are on the site, how you got here, what you click on, and information about your web browser. Your computer's IP address is masked (only a portion is stored) and personal information is only reported in aggregate. We do not allow Google to use or share our analytics data for any purpose besides providing us with analytics information.
  </p>

  <h4>Google’s Official Statement About Analytics Data</h4>
  <p>
    This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States . Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and Internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
  </p>

  <h4>Opting Out Of Analytics</h4>
  <p>
    If you are unhappy with the idea of sharing the fact you visited our sites (and any other sites) with Google, you can install the <a href="http://tools.google.com/dlpage/gaoptout"> official browser plugin for blocking Google Analytics</a>
  </p>

  <h3>Logging</h3>
  <p>
    We use logs to collect information about the state of the service in order to address bugs and improve the site. These logs may include details about your behavior at the time of an error, including your session information and your computer's IP address.
  </p>
  <h4>Bugsnag's DPA</h4>
  <p>
    We use Bugsnag to compile and analyse errors. These details are held by Busnag and may include your IP address. Bugsnag's data protection statement includes the following text:
  </p>
  <p>
    "a) Cross-Border Transfers of Personal Data. Customer authorizes Bugsnag and its Third Parties to transfer Customer Personal Data across international borders, including from the European Economic Area to the United States. Any cross-border transfer of Customer Personal Data must be supported by an approved adequacy mechanism. b) Privacy Shield Certification. Bugsnag is currently Privacy Shield certified, will maintain its Privacy Shield certification during the term of the Agreement and will Process the Customer Personal Data in accordance with at least the same level of protection as required under the applicable Privacy Shield principles. Bugsnag will provide written notification to Customer before it withdraws from or otherwise no longer maintains a current certification to the Privacy Shield. Bugsnag shall promptly notify Customer if it can no longer meet its obligations under this Section."
  </p>
  <p>
    You can read Bugnag's data protection addendum statement in full <a href='https://docs.bugsnag.com/legal/dpa/' target='_blank' rel="noopener"> on their website</a>
  </p>
  <h2>Your Rights</h4>
  <p>
    You can find out what information we hold about you, and ask us not to use any of the information we collect. Email <a href='mailto:privacy@octobox.io'>privacy@octobox.io</a> to request either of these.
  </p>

  <h2>Changes To This Privacy Policy</h4>
  <p>
    From time to time we may modify or update our privacy policy. We will do so by updating this page.
  </p>
</div>

<%= render 'layouts/footer'%>